# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "egycounter"
BBFILE_PATTERN_egycounter = "^${LAYERDIR}/"
BBFILE_PRIORITY_egycounter = "8"

LAYERDEPENDS_egycounter = "core openembedded-layer meta-python networking-layer"
LAYERSERIES_COMPAT_egycounter = "scarthgap"
